### ISSUE TITLE
Routes to upload Pdf

### ISSUE THREAD

**Issue by Souvikns** [cusm-tech/backend#11]
This has to be done only after issue #10

## Features to Implement
- [x] Create routes to upload pdf document into file storage. 
- [x] Create suitable algo to store records in the database for easy retrieval.

**Comment by Souvikns** [comment]
@aggarwaldev you were telling about some file type checking, it would be really good if you leave what to here, i will incorporate the changes accordingly, right now I am allowing all filetype to pass, really not changing any filetype.

**Comment by aggarwaldev** [comment]
I suggest you to go through:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
https://www.npmjs.com/package/multer#filefilter
